#!/c/MAMP/bin/ruby/bin/ruby.exe
# !/usr/env/bin ruby :(

# File:       cl
# Author:     Julian Orchard <hello@julianorchard.co.uk>
# Tag Added:  2022-04-20
# Desciption: Script to clock in and out at work, track hours, etc.

# Require
require 'date'

# Global Vars
$day_of_the_week_num = Time.now.strftime("%u")
$day_of_the_week_name = Time.now.strftime("%A")
$date_csv = Time.now.strftime("%d-%m-%Y")
$time_csv = Time.now.strftime("%H:%M")
$week_csv = Time.now.strftime("%V") # week, 01..53

$this_day = Date.today
$start_of_the_week = Date.today - (Date.today.wday + 1)
$log_file = "#$start_of_the_week.txt"


def usage
  puts
  puts "  -----------------------"
  puts "  CL - Track Hours Worked"
  puts "  -----------------------"
  puts
  puts "  in         clock in at this time"
  puts "  out        clock out at this time"
  puts "  fill       clock in and out, a standard day"
  puts
end

def start_of_the_week(input_date:)
  curr = Time.now.strftime("%u")
end

def l_array(str_line:,col:)
  # split into array
    str_line_values = str_line.split(",")
    return str_line_values[col]
    # week_number = 0
    # day_of_the_week = 1
    # full_date = 2
    # clock_in_time = 3
    # clock_out_time = 4
end

def find_row(action:)
  puts "Taking action '" + action + "'."
  File.open($log_file, "r") do |f|
    f.each_line do |l|
      if $week_csv == l_array(str_line:l,col:0)
        puts $date_csv + " and " + l_array(str_line:l,col:2)
        if $date_csv == l_array(str_line:l,col:2)
          puts "This is today, in fact..."
          row_exists = true
        end
      end
    end
  end
end

def new_week(action:)
  if action == "out"
    puts "You can't clock out if you've not clocked in yet"
    exit
  end
  puts "Recording a new day, a new week, a new life... for you."
  if $start_of_the_week == $this_day
    puts "Easy"
  else
    puts "Do you want to fill in the week up\nuntil now as holiday, or manually? (Y/n) "
    what_do = gets.chomp()
    if what_do == "y"
      puts "true"
    else
      puts "faulse"
    end
  end
end

def main
# Handle Args
  case ARGV[0]
  when "in"
    new_week(action:"in") if not File.file?($log_file)
    # find_row(action:"in")
  when "out"
    new_week(action:"out") if not File.file?($log_file)
    # find_row(action:"out")
  when "fill"
    find_row(action:"fill")
  else
    usage
    exit
  end
end

main

# vi: ft=ruby
